### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by alexdga** [seveas/yum_plugin_puppet#1]
Hello !

First thank you for releasing this module, it seems really interesting but i can't make it work.

I copied the directory in my module directory, the added Package { provider => 'yum3' } in my site site.pp and i get this error when running puppet agent --test : 

Error: Could not prefetch package provider 'yum3' : undefined method 'catalog' for nil:NilClass

I notified that the puppet run didn't try to create the files present in the files foler of the module.
I added include puppet-yum-plugin to my site.pp file, then on next run the files were correctly created but there's still the same error about provider 'yum3'.

**Comment by seveas** [comment]
Hi Alex,

You probably don't have a `package{"yum": ...}` anywhere in your recipe, which is mandatory for this plugin (and a good idea anyway. Even something as simple as `package{"yum": ensure => installed}` will do.

I'll amend the documentation to address both issues.

**Comment by alexdga** [comment]
It is now working using new steps in documentation.

Thank you

**Comment by alexdga** [comment]
Hi, it is now working without errors using your new documentation, but i
think it is not working as expected :

in my puppet dashboard, package execution time is about 59 seconds on a
total run of 72 seconds ...
there is always this message showing up during a run :

Notice: Puppet::Type::Package:ProviderYum3: Prefetch done (unable to
process 11 packages)....

I'm using ensure => purged in my package types, if i use absent puppet
can't handle dependencies and run fails ... (this is a bug in puppet i
think)

Thank you.

2013/11/19 Dennis Kaarsemaker notifications@github.com

**Comment by seveas** [comment]
Ah, the plugin doesn't support 'purged' yet (for the simple reason that I don't need it and forgot about purged). I've never heard of a bug that causes puppet to fail when using 'absent' though. Did you report this to puppetlabs?

**Comment by seveas** [comment]
Commit 7d607db adds support for purged, please try it and let me know if it works.
