### ISSUE TITLE
Does not honor --tags

### ISSUE THREAD

**Issue by reyjrar** [seveas/yum_plugin_puppet#2]
This plugin does not filter when running with "--tags module".  This can result in unexpected behavior when going between --noop and a normal run, especially since --noop does not report what modules the plugin would have installed.

**Comment by seveas** [comment]
Thanks Brad, I'll fix this after the X-mas holidays.

**Comment by seveas** [comment]
Fixed in 4ec6f3d - and internally, prefetch is disabled when --tags is given.
