### ISSUE TITLE
Is it still relevant, as of 2016?

### ISSUE THREAD

**Issue by gdubicki** [seveas/yum_plugin_puppet#8]
Hi Dennis! Thank you for this interesting piece of software! I just wonder is it still relevant as of 2016, with the current versions of Puppet 3.x and 4.x? PS I would have asked on your original blog post regarding this but comments seem not to work there...

**Comment by seveas** [comment]
Yes, even at the end of 2017 it's still relevant. Though the public version of this plugin needs some work and I've never tested it with puppet 4.x
